- name: conditions learning
  hosts: local
  connection: local
  vars:
    number: 30
  tasks:
    - name: print number greter than 100
      ansible.builtin.debug:
        msg: "number {{ number}} is less than 100"
      when: number > 100

    - name: print number greter than 100
      ansible.builtin.debug:
        msg: "number {{ number}} is greater than 100"
      when: number < 100