- name: Understand datatypes
  hosts: local
  connection: local
  vars:
    duration: 170 #number
    course: devops #string
    is_live: true  #boolean
    Tools: #list []
    - linux
    - shell
    - ansible 
    concepts: #map/dict/object {}
      CI: Jenkins
      Scripting: "shell,ansible,python"
  tasks:
    - name: print data types
      ansible.builtin.debug:
        msg: "course is {{ course }} duration is {{ duration }} is now live {{ is_live}} tools learning {{ tools }} and concepts learn {{ concepts }}"