- name: learning functions
  hosts: local
  connection: local
  vars:
    persons: Ramesh,Suresh,Raheem
  tasks:
    - name: learn functions
      vars:
        person: suresh
      debug:
        msg: "person is {{ person | default('Ramesh')}}"
  
    - name: print list as functions
      debug:
        msg: "persons are {{ persons | split(',') }}"

    - name: map into list
      vars:
        courses:
          name: ansible
          time: 20 min
          trainee: sweety
      debug:
        msg: "{{ courses | dict2items }}"