- name: learning functions
  hosts: local
  connection: local
  tasks:
    - name: learn functions
      vars:
        person: suresh
      debug:
        msg: "person is {{ person | default('Ramesh')}}"