- name: using shell vs command as module
  hosts: local
  connection: local
  tasks: 
  - name: redirect ls output theough pipe
    command: "ls -ltr"
    register: command_result
 
  - name: checl output is success
    debug:

      msg: "{ command_result }}"