- name: varaibles through prompt
  hosts: localhost
  connection: localhost
  vars_prompt:
    - name: username
      prompt: "please enter your name"
      private: true
    - name: password
      prompt: "please enter passwd"
      private: false
  tasks:
    - name: varaibles through prompt
      ansible.builtin.debug:
        msg: "hello username is {{ username }} password is {{ password }}" 